// Library Catalog Data & Helper Functions for Saranathan College Library

const BOOKS_CATALOG = [
  {
    id: 1,
    title: "1800 Mechanical Movements, Devices and Appliances",
    author: "Gardner D. Hiscox",
    category: "Mechanical Engineering",
    image: "1800 Mechanical Movements, Devices and Appliances (Dover Science Books).jpg",
    floor: "Floor 2",
    rack: "Rack M-04",
    shelf: "Shelf B",
    copies: 5,
    availableCopies: 4,
    isbn: "978-0486457741"
  },
  {
    id: 2,
    title: "71 Best Control System Books Technical Reference",
    author: "ISA Technical Reference",
    category: "Control Systems",
    image: "71 Best Control System Books of All Time (Updated___.jpg",
    floor: "Floor 3",
    rack: "Rack C-02",
    shelf: "Shelf A",
    copies: 4,
    availableCopies: 3,
    isbn: "978-1556179426"
  },
  {
    id: 3,
    title: "Algorithms in C++ Part 5: Graph Algorithms",
    author: "Robert Sedgewick",
    category: "Computer Science",
    image: "Algorithms in C++ Part 5_ Graph Algorithms.jpg",
    floor: "Floor 1",
    rack: "Rack CS-01",
    shelf: "Shelf C",
    copies: 8,
    availableCopies: 6,
    isbn: "978-0201361186"
  },
  {
    id: 4,
    title: "Beginning Ubuntu Linux: From Novice to Professional",
    author: "Keir Thomas & Andy Channelle",
    category: "Computer Science",
    image: "Beginning Ubuntu Linux_ From Novice to Professional (Beginning Series_ Open Source).jpg",
    floor: "Floor 1",
    rack: "Rack CS-05",
    shelf: "Shelf A",
    copies: 6,
    availableCopies: 4,
    isbn: "978-1590599914"
  },
  {
    id: 5,
    title: "Building Embedded Linux Systems",
    author: "Karim Yaghmour",
    category: "Embedded Systems",
    image: "Building Embedded Linux Systems_ Concepts, Techniques, Tricks, and Traps.jpg",
    floor: "Floor 2",
    rack: "Rack EC-03",
    shelf: "Shelf D",
    copies: 4,
    availableCopies: 2,
    isbn: "978-0596002220"
  },
  {
    id: 6,
    title: "C Programming Language: Step by Step Beginner's Guide",
    author: "Darrell L. Graham",
    category: "Programming",
    image: "C Programming_ Language_ A Step by Step Beginner's Guide to Learn C Programming in 7 Days.jpg",
    floor: "Floor 1",
    rack: "Rack CS-01",
    shelf: "Shelf A",
    copies: 10,
    availableCopies: 8,
    isbn: "978-1533612052"
  },
  {
    id: 7,
    title: "Cognitive Dependability Engineering",
    author: "Peter L. Jackson",
    category: "Cyber-Physical Systems",
    image: "Cognitive Dependability Engineering_ Managing Risks In Cyber-Physical-Social Systems Under Deep Uncertainty.jpg",
    floor: "Floor 3",
    rack: "Rack AI-02",
    shelf: "Shelf B",
    copies: 3,
    availableCopies: 3,
    isbn: "978-3030823405"
  },
  {
    id: 8,
    title: "Computational Thinking: A Beginner's Guide",
    author: "Karl Beecher",
    category: "Computer Science",
    image: "Computational Thinking_ A Beginner'S Guide To Problem-Solving And Programming.jpg",
    floor: "Floor 1",
    rack: "Rack CS-02",
    shelf: "Shelf B",
    copies: 7,
    availableCopies: 5,
    isbn: "978-1780173641"
  },
  {
    id: 9,
    title: "Computer Architecture: Digital Circuits to Computer Systems",
    author: "David Harris & Sarah Harris",
    category: "Hardware",
    image: "Computer Architecture_ Digital Circuits to….jpg",
    floor: "Floor 2",
    rack: "Rack EC-01",
    shelf: "Shelf C",
    copies: 6,
    availableCopies: 4,
    isbn: "978-0123944245"
  },
  {
    id: 10,
    title: "Control Systems Engineer Technical Reference Handbook",
    author: "ISA Society",
    category: "Control Systems",
    image: "Control Systems Engineer Technical Reference Handbook - ISA.jpg",
    floor: "Floor 3",
    rack: "Rack C-01",
    shelf: "Shelf D",
    copies: 5,
    availableCopies: 3,
    isbn: "978-1936007837"
  },
  {
    id: 11,
    title: "Control of Mechatronic Systems: Model-Driven Design",
    author: "Patrick O. J. Kaltjob",
    category: "Mechatronics",
    image: "Control of Mechatronic Systems_ Model-Driven Design and Implementation Guidelines.jpg",
    floor: "Floor 3",
    rack: "Rack M-05",
    shelf: "Shelf A",
    copies: 4,
    availableCopies: 2,
    isbn: "978-1119534723"
  },
  {
    id: 12,
    title: "Dominic Chinea Machines: A Visual History",
    author: "Dominic Chinea",
    category: "Mechanical Engineering",
    image: "Dominic Chinea Machines A Visual History (hardback) (uk Import).jpg",
    floor: "Floor 2",
    rack: "Rack M-02",
    shelf: "Shelf C",
    copies: 3,
    availableCopies: 3,
    isbn: "978-0241515907"
  },
  {
    id: 13,
    title: "Modern Mathematics for the Engineer",
    author: "Edwin F. Beckenbach",
    category: "Mathematics",
    image: "Dover Books on Engineering_ Modern Mathematics for the Engineer_ Second Series (Paperback) - Walmart_com.jpg",
    floor: "Floor 1",
    rack: "Rack MA-01",
    shelf: "Shelf B",
    copies: 8,
    availableCopies: 7,
    isbn: "978-0486497396"
  },
  {
    id: 14,
    title: "Engineering Calculation Pocket Book",
    author: "Tyler G. Hicks",
    category: "Engineering Reference",
    image: "Engineering Calculation Pocket Book_ Easy to Use Handbook for Engineers - Formulas, Equations and Mathematics.jpg",
    floor: "Floor 1",
    rack: "Rack GEN-01",
    shelf: "Shelf A",
    copies: 12,
    availableCopies: 9,
    isbn: "978-0071830805"
  },
  {
    id: 15,
    title: "Engineering Physics Complete Notes & Handbook",
    author: "Dr. A. S. Vasudeva",
    category: "Physics",
    image: "Engineering physics note.jpg",
    floor: "Floor 1",
    rack: "Rack PH-01",
    shelf: "Shelf D",
    copies: 15,
    availableCopies: 11,
    isbn: "978-8121923767"
  },
  {
    id: 16,
    title: "Essential Cybersecurity Science",
    author: "Josiah Dykstra",
    category: "Cybersecurity",
    image: "Essential Cybersecurity Science_ Build, Test, And Evaluate Secure Systems.jpg",
    floor: "Floor 3",
    rack: "Rack SEC-01",
    shelf: "Shelf A",
    copies: 5,
    availableCopies: 4,
    isbn: "978-1491920947"
  },
  {
    id: 17,
    title: "Exceptional C++: 47 Engineering Puzzles & Solutions",
    author: "Herb Sutter",
    category: "Programming",
    image: "Exceptional C++_ 47 Engineering Puzzles, Programming Problems, and Solutions.jpg",
    floor: "Floor 1",
    rack: "Rack CS-03",
    shelf: "Shelf B",
    copies: 6,
    availableCopies: 5,
    isbn: "978-0201615623"
  },
  {
    id: 18,
    title: "Fundamentals of Aerospace Engineering",
    author: "Manuel Soler",
    category: "Aerospace",
    image: "Fundamentals of Aerospace Engineering_ (Beginner's Guide).jpg",
    floor: "Floor 2",
    rack: "Rack AERO-01",
    shelf: "Shelf C",
    copies: 4,
    availableCopies: 3,
    isbn: "978-1499369069"
  },
  {
    id: 19,
    title: "How To Train Your Thinking: Sharpen Your Mind",
    author: "R. L. Adams",
    category: "General Reading",
    image: "How To Train Your Thinking_ Sharpen Your Mind To Think Bigger And Materialize Your Dreams.webp",
    floor: "Floor 1",
    rack: "Rack GEN-03",
    shelf: "Shelf A",
    copies: 5,
    availableCopies: 4,
    isbn: "978-1541019058"
  },
  {
    id: 20,
    title: "How to Build Impossible Things",
    author: "Mark Miodownik",
    category: "Innovation & Design",
    image: "How to Build Impossible Things.jpg",
    floor: "Floor 1",
    rack: "Rack DES-01",
    shelf: "Shelf B",
    copies: 4,
    availableCopies: 2,
    isbn: "978-0525537571"
  },
  {
    id: 21,
    title: "Interdisciplinary Mechatronics & Systems",
    author: "M. K. Habib",
    category: "Mechatronics",
    image: "Interdisciplinary Mechatronics - 19_99.jpg",
    floor: "Floor 3",
    rack: "Rack M-04",
    shelf: "Shelf C",
    copies: 3,
    availableCopies: 2,
    isbn: "978-1848215160"
  },
  {
    id: 22,
    title: "Learning Systems Thinking",
    author: "Diana Wright",
    category: "Systems Engineering",
    image: "Learning Systems Thinking.jpg",
    floor: "Floor 3",
    rack: "Rack SYS-01",
    shelf: "Shelf A",
    copies: 7,
    availableCopies: 6,
    isbn: "978-1605099255"
  },
  {
    id: 23,
    title: "Linux Bible: The Comprehensive Tutorial",
    author: "Christopher Negus",
    category: "Operating Systems",
    image: "Linux Bible.jpg",
    floor: "Floor 1",
    rack: "Rack OS-01",
    shelf: "Shelf A",
    copies: 9,
    availableCopies: 7,
    isbn: "978-1119578888"
  },
  {
    id: 24,
    title: "Linux for Beginners: Quick Command Line",
    author: "Jason Cannon",
    category: "Operating Systems",
    image: "Linux for Beginners_ An Introduction to the Linux….jpg",
    floor: "Floor 1",
    rack: "Rack OS-02",
    shelf: "Shelf B",
    copies: 12,
    availableCopies: 10,
    isbn: "978-1496145055"
  },
  {
    id: 25,
    title: "Modern Control Engineering 5th Edition",
    author: "Katsuhiko Ogata",
    category: "Control Systems",
    image: "Modern Control Engineering 5th Edition By Katsuhiko Ogata (PDF-Summary-Review-Online Reading-Download) - Toevolution.jpg",
    floor: "Floor 3",
    rack: "Rack C-03",
    shelf: "Shelf D",
    copies: 8,
    availableCopies: 5,
    isbn: "978-0136156734"
  },
  {
    id: 26,
    title: "Air Pollution Control Engineering",
    author: "Noel de Nevers",
    category: "Environmental",
    image: "NEVERS, Noel de_ Air pollution control….jpg",
    floor: "Floor 2",
    rack: "Rack ENV-01",
    shelf: "Shelf B",
    copies: 4,
    availableCopies: 3,
    isbn: "978-1478639206"
  },
  {
    id: 27,
    title: "Robotics: Modelling, Planning and Control",
    author: "Bruno Siciliano et al.",
    category: "Robotics",
    image: "Robotics_ Modelling, Planning and Control….jpg",
    floor: "Floor 3",
    rack: "Rack ROB-01",
    shelf: "Shelf A",
    copies: 6,
    availableCopies: 4,
    isbn: "978-1846286414"
  },
  {
    id: 28,
    title: "Robots and Robotics: Principles and Applications",
    author: "Mark R. Miller",
    category: "Robotics",
    image: "Robots and Robotics_ Principles, Systems, and Industrial Applications.jpg",
    floor: "Floor 3",
    rack: "Rack ROB-02",
    shelf: "Shelf C",
    copies: 5,
    availableCopies: 4,
    isbn: "978-1259859786"
  },
  {
    id: 29,
    title: "Shell Scripting: Automate Command Line Tasks",
    author: "Jason Cannon",
    category: "Operating Systems",
    image: "Shell Scripting_ How to Automate Command Line….jpg",
    floor: "Floor 1",
    rack: "Rack OS-03",
    shelf: "Shelf A",
    copies: 7,
    availableCopies: 5,
    isbn: "978-1517300760"
  },
  {
    id: 30,
    title: "Structural Dynamics: Volume 50",
    author: "Peretz P. Friedmann et al.",
    category: "Civil Engineering",
    image: "Structural Dynamics_ Volume 50 _ Peretz P_ Friedmann,George A. Lesieutre,Daning Huang",
    floor: "Floor 2",
    rack: "Rack CIV-01",
    shelf: "Shelf D",
    copies: 3,
    availableCopies: 2,
    isbn: "978-3319297620"
  },
  {
    id: 31,
    title: "The Algorithm Design Manual",
    author: "Steven S. Skiena",
    category: "Algorithms",
    image: "The Algorithm Design Manual by Steve S_ Skiena.jpg",
    floor: "Floor 1",
    rack: "Rack CS-04",
    shelf: "Shelf A",
    copies: 10,
    availableCopies: 8,
    isbn: "978-1848000698"
  },
  {
    id: 32,
    title: "The Book of Basic Machines",
    author: "U.S. Navy Bureau of Naval Personnel",
    category: "Mechanical Engineering",
    image: "The Book of Basic Machines ebook by U_S. Navy - Rakuten Kobo",
    floor: "Floor 2",
    rack: "Rack M-01",
    shelf: "Shelf B",
    copies: 6,
    availableCopies: 5,
    isbn: "978-0486217093"
  },
  {
    id: 33,
    title: "The Physics of Everyday Things",
    author: "James Kakalios",
    category: "Physics",
    image: "The Physics of Everyday Things_ The Extraordinary Science Behind an Ordinary Day.jpg",
    floor: "Floor 1",
    rack: "Rack PH-02",
    shelf: "Shelf C",
    copies: 5,
    availableCopies: 4,
    isbn: "978-0735216105"
  },
  {
    id: 34,
    title: "Think Like An Engineer",
    author: "Mushtak Al-Atabi",
    category: "General Engineering",
    image: "Think Like An Engineer_ Inside the Minds that are Changing our Lives.jpg",
    floor: "Floor 1",
    rack: "Rack GEN-02",
    shelf: "Shelf B",
    copies: 8,
    availableCopies: 6,
    isbn: "978-1482824247"
  },
  {
    id: 35,
    title: "Thinking in Algorithms",
    author: "Rutherford Birchard",
    category: "Algorithms",
    image: "Thinking in Algorithms_ How to Combine Computer Analysis and Human Creativity for Better Problem-Solving and Decision-Making.jpg",
    floor: "Floor 1",
    rack: "Rack CS-04",
    shelf: "Shelf B",
    copies: 7,
    availableCopies: 6,
    isbn: "978-1794501234"
  },
  {
    id: 36,
    title: "Analog Circuits (World Class Designs)",
    author: "Robert A. Pease",
    category: "Electronics",
    image: "[PDF] Analog Circuits (World Class Designs).jpg",
    floor: "Floor 2",
    rack: "Rack EC-04",
    shelf: "Shelf A",
    copies: 5,
    availableCopies: 3,
    isbn: "978-0750686273"
  },
  {
    id: 37,
    title: "Theory of Applied Robotics: Kinematics & Control",
    author: "Reza N. Jazar",
    category: "Robotics",
    image: "كتاب Theory of Applied Robotics - Kinematics, Dynamics, and Control.webp",
    floor: "Floor 3",
    rack: "Rack ROB-03",
    shelf: "Shelf B",
    copies: 4,
    availableCopies: 3,
    isbn: "978-1441917492"
  },
  {
    id: 38,
    title: "Manufacturing Engineering Special Edition",
    author: "SME Society of Manufacturing",
    category: "Manufacturing",
    image: "September 2012 issue_ www.MfgEngMedia.com",
    floor: "Floor 2",
    rack: "Rack M-03",
    shelf: "Shelf A",
    copies: 4,
    availableCopies: 4,
    isbn: "978-0872638525"
  },
  {
    id: 39,
    title: "Vintage Engineering Book Cover Reference",
    author: "Classic Archive",
    category: "Design",
    image: "old Book Cover Design for Authors & Self‑Publishers.jpg",
    floor: "Floor 1",
    rack: "Rack ART-01",
    shelf: "Shelf C",
    copies: 2,
    availableCopies: 2,
    isbn: "978-0001122334"
  },
  {
    id: 40,
    title: "Advanced Sensor Networks & Facility Management",
    author: "Industrial IoT Group",
    category: "IoT & Sensors",
    image: "🛠️ Facility managers_ Use sensors to detect….jpg",
    floor: "Floor 3",
    rack: "Rack AI-03",
    shelf: "Shelf C",
    copies: 6,
    availableCopies: 5,
    isbn: "978-3030112234"
  },
  {
    id: 41,
    title: "Stark Tech Advanced System Architecture",
    author: "Anthony E. Stark",
    category: "Artificial Intelligence",
    image: "tony stark.webp",
    floor: "Floor 3",
    rack: "Rack AI-01",
    shelf: "Shelf A",
    copies: 5,
    availableCopies: 5,
    isbn: "978-0785123456"
  },
  {
    id: 42,
    title: "Keep Your Spirit: Mindset & Resilience",
    author: "Muth Boravy",
    category: "General Reading",
    image: "Muth Boravy, Keep Your Spirit_.webp",
    floor: "Floor 1",
    rack: "Rack GEN-04",
    shelf: "Shelf D",
    copies: 4,
    availableCopies: 4,
    isbn: "978-9995012345"
  },
  {
    id: 43,
    title: "Christmas System UI & App Icon Engineering",
    author: "Creative Tech Guild",
    category: "UI/UX Design",
    image: "Christmas Ios 14 Homescreen - Christmas App Icon - Christmas App Icons.jpg",
    floor: "Floor 1",
    rack: "Rack DES-02",
    shelf: "Shelf A",
    copies: 3,
    availableCopies: 3,
    isbn: "978-1234567890"
  },
  {
    id: 44,
    title: "Advanced Machine Learning Foundations",
    author: "Deep Learning Research Unit",
    category: "Artificial Intelligence",
    image: "15833036179123253.jpg",
    floor: "Floor 3",
    rack: "Rack AI-02",
    shelf: "Shelf D",
    copies: 6,
    availableCopies: 4,
    isbn: "978-0262035613"
  },
  {
    id: 45,
    title: "Quantum Computing for Engineers",
    author: "Nielsen & Chuang",
    category: "Computer Science",
    image: "16395986135270484.jpg",
    floor: "Floor 1",
    rack: "Rack CS-06",
    shelf: "Shelf A",
    copies: 5,
    availableCopies: 3,
    isbn: "978-1107002173"
  },
  {
    id: 46,
    title: "Data Science & Big Data Analytics",
    author: "EMC Education Services",
    category: "Data Science",
    image: "17662623526792877.jpg",
    floor: "Floor 1",
    rack: "Rack DS-01",
    shelf: "Shelf B",
    copies: 8,
    availableCopies: 6,
    isbn: "978-1118876138"
  },
  {
    id: 47,
    title: "VLSI Circuit Design Fundamentals",
    author: "Sung-Mo Kang",
    category: "Electronics",
    image: "19140367162786879.webp",
    floor: "Floor 2",
    rack: "Rack EC-02",
    shelf: "Shelf C",
    copies: 7,
    availableCopies: 5,
    isbn: "978-0072460704"
  },
  {
    id: 48,
    title: "Signals and Systems 2nd Edition",
    author: "Alan V. Oppenheim",
    category: "Electronics",
    image: "227854062384195688.jpg",
    floor: "Floor 2",
    rack: "Rack EC-01",
    shelf: "Shelf B",
    copies: 10,
    availableCopies: 8,
    isbn: "978-0138147570"
  },
  {
    id: 49,
    title: "Database System Concepts 7th Edition",
    author: "Silberschatz, Korth & Sudarshan",
    category: "Computer Science",
    image: "269582727689726415.jpg",
    floor: "Floor 1",
    rack: "Rack CS-02",
    shelf: "Shelf D",
    copies: 12,
    availableCopies: 9,
    isbn: "978-0078022159"
  },
  {
    id: 50,
    title: "Computer Networks: System Approach",
    author: "Larry L. Peterson",
    category: "Networking",
    image: "2744449769437942.jpg",
    floor: "Floor 1",
    rack: "Rack NET-01",
    shelf: "Shelf A",
    copies: 9,
    availableCopies: 7,
    isbn: "978-0123850591"
  },
  {
    id: 51,
    title: "Digital Image Processing 4th Edition",
    author: "Rafael C. Gonzalez",
    category: "Computer Science",
    image: "339669996917645733.jpg",
    floor: "Floor 3",
    rack: "Rack AI-04",
    shelf: "Shelf B",
    copies: 6,
    availableCopies: 4,
    isbn: "978-0133356724"
  },
  {
    id: 52,
    title: "Operating System Concepts 10th Edition",
    author: "Silberschatz & Galvin",
    category: "Operating Systems",
    image: "703617141800061904.jpg",
    floor: "Floor 1",
    rack: "Rack OS-01",
    shelf: "Shelf C",
    copies: 14,
    availableCopies: 11,
    isbn: "978-1118063330"
  },
  {
    id: 53,
    title: "Thermal Engineering & Thermodynamics",
    author: "R. K. Rajput",
    category: "Mechanical Engineering",
    image: "711639178668335549.webp",
    floor: "Floor 2",
    rack: "Rack M-01",
    shelf: "Shelf D",
    copies: 8,
    availableCopies: 6,
    isbn: "978-8131808047"
  },
  {
    id: 54,
    title: "Renewable Energy Technology & Power",
    author: "Godfrey Boyle",
    category: "Electrical Engineering",
    image: "727120302347428706.jpg",
    floor: "Floor 2",
    rack: "Rack EE-02",
    shelf: "Shelf A",
    copies: 5,
    availableCopies: 4,
    isbn: "978-0199545339"
  },
  {
    id: 55,
    title: "Power Electronics: Circuits & Devices",
    author: "Muhammad H. Rashid",
    category: "Electrical Engineering",
    image: "791366965808943978.jpg",
    floor: "Floor 2",
    rack: "Rack EE-01",
    shelf: "Shelf C",
    copies: 7,
    availableCopies: 5,
    isbn: "978-0133125900"
  },
  {
    id: 56,
    title: "Artificial Intelligence: Modern Approach",
    author: "Stuart Russell & Peter Norvig",
    category: "Artificial Intelligence",
    image: "92605336081364053.jpg",
    floor: "Floor 3",
    rack: "Rack AI-01",
    shelf: "Shelf A",
    copies: 15,
    availableCopies: 12,
    isbn: "978-0134610992"
  },
  {
    id: 57,
    title: "Deep Learning Foundations & Applications",
    author: "Ian Goodfellow & Yoshua Bengio",
    category: "Artificial Intelligence",
    image: "939493172276013197.jpg",
    floor: "Floor 3",
    rack: "Rack AI-02",
    shelf: "Shelf B",
    copies: 11,
    availableCopies: 9,
    isbn: "978-0262035614"
  },
  {
    id: 58,
    title: "Special Collections Book Reference",
    author: "Saranathan Central Library",
    category: "General Engineering",
    image: "Only 8 left and in 6 carts.jpg",
    floor: "Floor 1",
    rack: "Rack REF-01",
    shelf: "Shelf A",
    copies: 4,
    availableCopies: 3,
    isbn: "978-0000001122"
  }
];

if (typeof window !== 'undefined') {
  window.BOOKS_CATALOG = BOOKS_CATALOG;
}
